# Generated by Django 6.1.1 on 2026-09-16 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_city', models.CharField(default='Maturín', help_text='Ciudad operacional donde el usuario busca ofertas de compra.', max_length=100)),
                ('min_budget', models.DecimalField(decimal_places=2, default=100.0, help_text='Presupuesto mínimo asignado para compra por dispositivo ($).', max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, default=250.0, help_text='Presupuesto máximo asignado para compra por dispositivo ($).', max_digits=10)),
                ('min_profit', models.DecimalField(decimal_places=2, default=30.0, help_text='Margen de ganancia neta mínima deseada por dispositivo ($).', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
