# Generated by Django 6.1.1 on 2026-09-16 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUALIFIED', '🟢 Oportunidad Aprobada'), ('LOW_PROFIT', '🟡 Ganancia Insuficiente'), ('OVER_BUDGET', '🟠 Excede Presupuesto'), ('NON_OPERATIONAL', '🔴 Fuera de Ciudad Operacional')], default='QUALIFIED', max_length=30)),
                ('projected_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_resale_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_repairs_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('explanation_code', models.CharField(help_text='Código corto de explicación (ej. HIGH_PROFIT, LOW_MARGIN).', max_length=50)),
                ('explanation_text', models.TextField(help_text='Explicación detallada para el usuario.')),
                ('is_favorite', models.BooleanField(default=False, help_text='Guardado en la lista de ofertas destacadas.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidad de Compra',
                'verbose_name_plural': 'Oportunidades de Compra',
                'ordering': ['-projected_profit', '-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
