# Generated by Django 6.1.1 on 2026-09-16 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('FB_MARKETPLACE', 'Facebook Marketplace'), ('WHATSAPP_GROUPS', 'Grupos / Estados de WhatsApp'), ('AMAZON_REFURBISHED', 'Amazon Refurbished (Referencia)'), ('MANUAL_IMPORT', 'Importación Manual')], default='FB_MARKETPLACE', max_length=50)),
                ('raw_title', models.CharField(max_length=255)),
                ('listing_url', models.URLField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(help_text='Ciudad de origen de la publicación.', max_length=100)),
                ('asking_price_usd', models.DecimalField(decimal_places=2, help_text='Precio pedido ($ USD).', max_digits=10)),
                ('battery_health_pct', models.IntegerField(blank=True, help_text='Porcentaje de salud de batería (%).', null=True)),
                ('screen_condition', models.CharField(choices=[('INTACT', 'Intacta / Impecable'), ('SCRATCHED', 'Con Rayaduras'), ('CRACKED', 'Pantalla / Mica Rota')], default='INTACT', max_length=20)),
                ('body_condition', models.CharField(choices=[('INTACT', 'Impecable'), ('SCRATCHED', 'Detalles Estéticos / Rayones'), ('DAMAGED', 'Golpeado / Abollado')], default='INTACT', max_length=20)),
                ('face_id_working', models.BooleanField(default=True, help_text='¿Face ID / Touch ID funciona?')),
                ('camera_working', models.BooleanField(default=True, help_text='¿Cámara principal y frontal funcionan correctamente?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Usuario propietario de la publicación.', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(help_text='Variante exacta de iPhone (Modelo + Almacenamiento + Color).', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Publicación de iPhone',
                'verbose_name_plural': 'Publicaciones de iPhones',
                'ordering': ['-captured_at'],
            },
        ),
    ]
