# Generated by Django 6.1.1 on 2026-09-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de la imagen principal del anuncio.', max_length=1000, null=True),
        ),
    ]
