# Generated by Django 6.1.1 on 2026-09-16 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_premium_tier', models.BooleanField(default=False, help_text='Indica si es un color de alta demanda (ej. Blanco / Plata).')),
            ],
            options={
                'verbose_name': 'Clasificación de Color',
                'verbose_name_plural': 'Clasificaciones de Color',
            },
        ),
        migrations.CreateModel(
            name='IPhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre exacto del modelo de iPhone.', max_length=100, unique=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Modelo de iPhone',
                'verbose_name_plural': 'Modelos de iPhone',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gb', models.IntegerField(help_text='Capacidad de almacenamiento en Gigabytes (GB).', unique=True)),
            ],
            options={
                'verbose_name': 'Capacidad de Almacenamiento',
                'verbose_name_plural': 'Capacidades de Almacenamiento',
                'ordering': ['gb'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_reference_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de referencia base global o de Amazon Used ($).', max_digits=10, null=True)),
                ('color_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.colortier')),
                ('iphone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.iphonemodel')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.storagecapacity')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'unique_together': {('iphone_model', 'storage', 'color_tier')},
            },
        ),
    ]
